### ISSUE TITLE
inline serializeToRaw and unserializeFromRaw

### ISSUE THREAD

**Issue by richfitz** [eddelbuettel/rapiserialize#2]
Is there a reason why `serializeToRaw` and `unserializeFromRaw` are not declared inline?  Including `RApiSerializeAPI.h` in more than one `.cpp` file causes duplicate symbols on linking, unless I'm doing something wrong.

I can send a trivial PR but wondered if I was missing something.

**Comment by richfitz** [comment]
To be clear:

line [50](https://github.com/eddelbuettel/rapiserialize/blob/master/inst/include/RApiSerializeAPI.h#L50) becomes

``` c
inline SEXP attribute_hidden serializeToRaw(SEXP x) {
```

and line [56](https://github.com/eddelbuettel/rapiserialize/blob/master/inst/include/RApiSerializeAPI.h#L56) becomes

``` c
inline SEXP attribute_hidden unserializeFromRaw(SEXP x) {
```

**Comment by eddelbuettel** [comment]
Seems like non-issue to me: I have one file consuming serialization, and that file includes the header.  Object code comes from R.

In short I haven't had a need for change, but I have a need for this code working as it is in production.

**Comment by richfitz** [comment]
It's an issue for me if `RApiSerializeAPI.h` is itself listed in a header, which was the case with toying around with RcppRedis.  I can work around it though if you don't want it changed.  However, I don't think that change should break anything?

**Comment by eddelbuettel** [comment]
RcppRedis does not export a header. It imports RApiSerialize.

If you use RApiSerialize somewhere, try importing the header once and just once.  We could make it inline but because the code isn't actually inlined ... it is a bit of a kludge.

**Comment by richfitz** [comment]
Sorry - I'm being unclear.  I'm reworking RcppRedis to use RcppR6 to see if I can eke out a bit more performance (looks like ~10% but a 10x faster package load and avoids the "no function to return from" error that I think is probably a modules bug) and that moves a lot of the code into the headers.  I'm trying to make as few changes to the package as possible to introduce as few possible new bugs so am avoiding splitting the class declaration and definition and that leads to including RApiSerialize twice.  but I've worked around that and included it only once.  I now see that there's some intricacies with that function with getting loaded dynamically as an alternative to linking or something?

**Comment by eddelbuettel** [comment]
With all due respect, your paragraph only notes that you appear to have some issue somewhere in some code you moved around from somewhere else. Nothing to look at, nothing reproducible.  How am I to help?

Maybe just do what you need to do.  I wrote RApiSerialize because RcppRedis needed it just how I wrote RcppRedis because I needed it for some work. Both do what I want them them to; you will have to make a case that change is better to everyone with limited to little cost to me.   

I am not trying to be difficult but you are not supplying easy to evaluate change requests.  And sorry, have a SWC unit coming up so we can't play issue ticket ping pong now. 

I remain very interested in RcppR6.  I may just be short of time right now to study things at great length.

**Comment by richfitz** [comment]
> With all due respect

As an Englishman, that's harsh :sweat_smile:

Sorry about being vague - doing the port was kind of an all or nothing thing so wanted to see how I'd get it done rather than push broken code.

Changes are up now here: https://github.com/richfitz/rcppredis/commit/698227758e176a2c06be28fdc4dc1e6856172ddb#commitcomment-10726759 - the link points at a comment on the commit that outlines pros and cons.

Once you have more time and if you're interested I can open a PR on RcppRedis, but in the mean time please close this one if it's not something that you're interested in, especially as it's now totally not on topic.

**Comment by eddelbuettel** [comment]
That's picture-perfect. I'll just take a "static" clone, and try to build and run it.  Does it still use the same name, so it would replace my RcppRedis?  Maybe RcppRedisAlt or RcppRedisRich or something to have them coexist may help.  Anyway ...

**Comment by eddelbuettel** [comment]
Speaking about _harsh_, in case you don't follow [Very British Problems](https://twitter.com/SoVeryBritish) on Twitter then you really ought to ;-)

**Comment by richfitz** [comment]
I'm renaming it now; will be up in a couple of minutes.

**Comment by richfitz** [comment]
OK, [up now](https://github.com/richfitz/rcppredis/tree/RcppR6).  Passes tests/R CMD check for me and I can see the redis chatter with `redis-cli monitor`.

**Comment by eddelbuettel** [comment]
This breaks:

```
#include "../inst/include/RcppR6Redis.h"
```

**Comment by eddelbuettel** [comment]
Effing OS X -- `RcppR6Redis/RcppR6_pre.hpp`  needed a capital R for Redis.  You had `r`.

**Comment by richfitz** [comment]
Oh wow, that's terrible.  I was trying to work out why that wasn't working while the same approach was working on other packages.

**Comment by eddelbuettel** [comment]
No worries.  I've seen this before -- and Travis helps with that.  Side effect of the renaming, so "my fault" anyway ;-)

**Comment by eddelbuettel** [comment]
That looks pretty nice so far. I don't understand it all yet, and my main db is at work anyway but thumbs up so far...

**Comment by richfitz** [comment]
Great! All the complicated bits are in [RcppR6_support.hpp](https://github.com/richfitz/rcppredis/blob/RcppR6/inst/include/RcppR6Redis/RcppR6_support.hpp) - once that's in place the as/wrap templates are pretty straightforward.  I make no claim that it's the fastest or best way of doing things, but it has proved robust so far.

**Comment by eddelbuettel** [comment]
I'll need a few more tutorials from you as (Rcpp)R6 is very new to me too.

**Comment by richfitz** [comment]
At long last I have started on tutorials.  First one is up [here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/richfitz/RcppR6/master/inst/doc/introduction.html)

**Comment by eddelbuettel** [comment]
:+1:

**Comment by eddelbuettel** [comment]
> (note that the package here is called README, as this is the package used in generating the README for RcppR6 - OK that’s probably confusing).

Yup :)

**Comment by richfitz** [comment]
Fixed - always good to have confirmation :)

**Comment by eddelbuettel** [comment]
This can be closed for general staleness.
