### ISSUE TITLE
Compatibility issue when qs::qsave a data.table object

### ISSUE THREAD

**Issue by qzhang503** [eddelbuettel/rapiserialize#4]
qs::qsave(data.table::data.table(mtcars), "foo.qs", preset = "fast")

**Comment by eddelbuettel** [comment]
Hi there.  Maybe that would be better asked at the [qs](https://github.com/traversc/qs) repo?

@traversc and I are aware of a possible side effect of _installing `RApiSerialize` without rebuilding `qs`_.  Is that what you did?  If both are rebuilt things should work.  In fact, on my box (everything current, `qs` just reinstalled) the above also works:

```r
> qs::qsave(data.table::data.table(mtcars), "/tmp/foo.qs", preset = "fast")
> 
```

**Comment by qzhang503** [comment]
Hi Eddelbuettel,

Looks like the next version of qs will be compatible with RApiSerialize
0.1.1. Thank you very much for your time.

Qiang Zhang

**Comment by eddelbuettel** [comment]
Yep.  @traversc and I think we are on top of it.

**Comment by eddelbuettel** [comment]
And thanks to @traversc for pushing a new version to CRAN.
