### ISSUE TITLE
Add a simple C++ namespace in the exporting header

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rapiserialize#8]
At the same time, maybe clean up between 'full' three-argument version of `serializeToRaw` (with rarely used arguments version and use_xdr) and a simpler one-argument version.  

Ideally without breaking anything.   RcppRedis is easy to adjust for me.

**Comment by eddelbuettel** [comment]
@traversc if I were to send you a PR to package `qs` after getting the change in [this variant of RApiSerialize.h](https://github.com/eddelbuettel/rapiserialize/blob/feature/api_enhancement/inst/include/RApiSerializeAPI.h) to CRAN, would you be ok with that?    I recently realized that the interface to RApiSerialize works from C++ (we can drop the optional arguments) but not in C and as the file is (also) meant for C I should fix that.  At the same time, adding a C++ is a nice touch which is done in one or two other header-exporting packages, and it allows for optional use as you and I had done all along in RcppRedis and qs.  So the PR would keep the same header but call `rapi::serializeToRaw` where it is currently just `serializeToRaw`.  It should support one, two or three argument calls via the (then "more official") C++ interface.

Congrats also on qs2 which I have to look at more closely myself.  Looks like you wrote a serializer for it?

**Comment by traversc** [comment]
Hi Dirk, I'd very much welcome a PR!

When are you planning to submit the update to CRAN? I'd like to also work in some other changes to `qs`, especially looking at the API restrictions. 

> Congrats also on qs2 which I have to look at more closely myself. Looks like you wrote a serializer for it?

Thanks! The main reason for working on a successor is the API restrictons. I think I need some of those internal calls to get serialization right... and it's time consuming to make sure it works with each new R update (internals getting changed means serialization can change). 

The package has two formats: `qs2`, which is just multi-threaded block compression on top of `R_Serialize`. This is really a good 80/20 solution and doesn't require any update to make sure it works into the future.

But because there are inefficiencies with `R_Serialize` I also have the `qdata` format. This is a spiritual successor to 'qs' where I write my own `serialize` layer, but only serializing data objects (vectors, dataframes, lists, matrices) so as not to run into API restrictions. In my benchmarks, this performs better than anything else out there... but those benchmarks could be biased ;)

**Comment by eddelbuettel** [comment]
Hi Travers,

No timeline, and no urgency.  This arose from some work in `digest` and possibly exposing more use at the C(++) layer which got `RApiSerialize` involved and then I saw with some horror that I got the C API wrong ... as it only works in C++.  So minor desire to clean things up.

I can take care of `RcppRedis`, and `qs` is the only other user.  And I think the cleanest would be for
- `RApiSerialize` to offer a new interface, and we get that to CRAN
- then update the two client packages taking care of it
- and then clean up the old interface (which pretends to allow one argument, but that requires C++)

I may change the C++ namespace from the current `rapi::` to use just `R::` which I do in one or two other places.  Cleaner.

**Comment by eddelbuettel** [comment]
>  I may change the C++ namespace from the current rapi:: to use just R:: which I do in one or two other places. Cleaner.

Done.

**Comment by traversc** [comment]
@eddelbuettel I went ahead and updated `qs` with the `R::` namespace. Ready to submit to CRAN whenever you are!

**Comment by eddelbuettel** [comment]
Great -- in which case I'll send this to CRAN today, most likely.

**Comment by eddelbuettel** [comment]
Now on CRAN so `qs` and `RcppRedis` can depend on it.

**Comment by traversc** [comment]
That was quick!

The C linkage functions without the `R::` namespace are still exported so it's still possible to do:
```
// [[Rcpp::export]]
SEXP test(SEXP x) { return serializeToRaw(x); } // no namespace
```

```
packageVersion("RApiSerialize")
test(42)
// [1] ‘0.1.4’
// [1] 58 0a 00 00 00 02 00 04 04 01 00 02 03 00 00 00 00 0e 00 00 00 01 40 45 00 00 00 00 00 00
```
So updates to qs aren't strictly necessary. Is this intended to provide both C and C++ linkage when using C++?

**Comment by eddelbuettel** [comment]
Yes, this will remain exported (backwards compatibility and all) but I may remove the two default arguments (see below).

Now, I suspect what you inclided above you included in a C++ file -- so we still support what always worked.  But it was only more recently that I realized that that same usage pattern does _not_ work when included in a C file (ie also no Rcpp::export niceties).

And 'updates to qs aren't strictly necessary':  yes and no.  If you switch to the C++ namespace use I think you will be better protected when I do this next:

```diff
modified   inst/include/RApiSerializeAPI.h
@@ -51,8 +51,7 @@ extern "C" {
 /* provided the interface for the function exported 	*/
 /* in ../src/init.c via R_RegisterCCallable()		*/
 
-SEXP attribute_hidden serializeToRaw(SEXP x, SEXP ver = R_NilValue,
-                                     SEXP use_xdr = R_NilValue) {
+SEXP attribute_hidden serializeToRaw(SEXP x, SEXP ver, SEXP use_xdr) {
     static SEXP(*fun)(SEXP, SEXP, SEXP) =
         (SEXP(*)(SEXP,SEXP,SEXP)) R_GetCCallable("RApiSerialize", "serializeToRaw");
     return fun(x, ver, use_xdr);

```

Could you check that?

**Comment by traversc** [comment]
Ah I see what you mean, I misunderstood. Anyway just submitted the update, fingers crossed it gets through!

**Comment by eddelbuettel** [comment]
And it got there yesterday as [CRANberries](http://dirk.eddelbuettel.com/cranberries/2024/10/01#qs_0.27.2) noticed so I may now follow-up with the cleanup -- in two or three days to give this one the weekly-at-least cadence.
